on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - '**'

name: tests
env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go-version:
          # support the two most recent major go versions
          - 1.x
          - 1.19.x
          - 1.18.x
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      #- name: Run integration tests
        #run: make integrations

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=120m
